@FormaaS_HostAddress = http://localhost:5014

###
GET {{FormaaS_HostAddress}}/forms/

###
POST {{FormaaS_HostAddress}}/forms/
Content-Type: application/json

{
    "Name": "Users",
    "Fields": [
        {
        "Id": "39bea9b4-0fb7-4e7d-8582-7dcc59cb3fdd",
        "Name": "Name",
        "Type": "TextInput",
        "Required": true,
        "Details": {
            "MinLength": 1,
            "MaxLength": 10
        }
        },
      {
        "Id": "39bea9b4-0fb7-4e7d-8582-7dcc59cb3fdd",
        "Name": "Age",
        "Type": "NumberInput",
        "Required": true,
        "Details": {
            "MinValue": 1,
            "MaxValue": 100
        }
      }
    ]
}

###
PUT {{FormaaS_HostAddress}}/forms/1
Content-Type: application/json

{
  "Name": "Form 01",
  "Fields": [
    {
      "Id": "39bea9b4-0fb7-4e7d-8582-7dcc59cb3fdd",
      "Name": "Name 2",
      "Type": "TextInput",
      "Required": true,
      "Details": {
        "MinLength": 1,
        "MaxLength": 10
      }
    }
  ]
}

###
POST {{FormaaS_HostAddress}}/forms/1/submit
Content-Type: application/json

[
  {
    "FieldId": "4d19175d-96db-4cd1-864f-3308dde6baa4",
    "Value": "Nam"
  },
  {
    "FieldId": "0ddf4f64-c2be-4ac7-981d-ee955ea36460",
    "Value": 28
  }
]