###
POST https://localhost:5024/auth/login/github

###
GET https://localhost:5024/auth/AuthFlowInfo?provider=GitHub

###
POST https://localhost:5024/login/
Content-Type: application/json

{
"email":"pvnam95@hotmail.com",
"password":"oCvZX&ZWXk73LM"
}

###
GET https://localhost:5024/jwks.json

###
POST https://localhost:5024/Introspections/TokenIntrospect

###
POST https://localhost:5024/auth/login/github
