GET http://localhost:5209/test/ping
Authorization: Bearer CfDJ8OcABFE1SvBChKHsxxdKNIa7ZjyGAyGaHYy8jhKUel00cBRL3P7yTZFT7FVJ1Su5K8FeJr-nJsENHG-vOywL2IngZV6HQ4Y1Q-a2JOAWazSesAPXaEklf4ZY4peIxktebyqPKVCo1GNspUXouVLUEQ67FAngkyvGmgYBoopfIIye45v2AFawHlFmz50ZhhQqgRCr4i8WXPLQa9lOw9UPzC9BclPmu_x8wWsfCOg73Q0dJCIvWT-FecwTBp_x7uCKgTESX5VaHDBHErX1hjNC24pZ84LPT1dM11Gpx0wPYMm-8fuDTXW4ZbSDEUWosuFj-caT-BwH33zhGGvvN-ZxHD7I0NV6iZVAzO1niF0IjM-NSlnNScsXYxFn1RT5vLN4sRJaX3-C0lMRSPWxDc7tAZh7ko9UhDvf22UiJRIRg1mOUrpKy7lI-j715bsZkM1UR5bq1ONz93Pdxad-ey1VBikcbauCbJP2mDuQ6ZargIOCIWBqrVMoOhQRyxGMN7Xn_Dw7XmlEqZKY4b2Pz62FO3I_HWezDL3POBRBcPFwg8nRBI9UKPWEo57bQvxslo_dYBprz0wXRPLU6EoLNwhW-rjqFMrjpzSAxddZXAr1VVnqKkIh-lHI_lnEW0G0tVqdbbR1tKWEi5VdfZKUfHd5ME6b0h_OPjkkXdEg89BPUOk2Z3cJom4U063_UUU7eXa07KhFg082hSMdtG4iFDVxSPw 
